# Generated by Django 4.1.5 on 2023-01-09 06:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('resume', models.CharField(max_length=150, verbose_name='Resumen')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='proyects/image', verbose_name='Imagen')),
                ('link_github', models.URLField(verbose_name='Link GitHub')),
                ('languages', models.ManyToManyField(blank=True, null=True, to='portafolio.language', verbose_name='Lenguajes')),
            ],
            options={
                'verbose_name': 'Projecto',
                'verbose_name_plural': 'Projectos',
            },
        ),
        migrations.DeleteModel(
            name='Proyect',
        ),
    ]
