# Generated by Django 4.1.5 on 2023-01-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_project_delete_proyect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='media/image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(blank=True, to='portafolio.language', verbose_name='Lenguajes'),
        ),
    ]
