# Generated by Django 4.1.5 on 2023-01-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_project_image_alter_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_project',
            field=models.URLField(null=True, verbose_name='Link Proyecto'),
        ),
    ]
