# Generated by Django 4.1.5 on 2023-01-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_project_link_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_project',
            field=models.URLField(blank=True, null=True, verbose_name='Link Proyecto'),
        ),
    ]
