# Generated by Django 4.1.5 on 2023-01-20 08:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portafolio', '0003_alter_project_image_alter_project_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre completo')),
                ('image_front', models.ImageField(upload_to='media/image', verbose_name='Imagen perfil')),
                ('image_logo', models.ImageField(upload_to='media/image', verbose_name='Imagen Logo')),
                ('job', models.CharField(max_length=200, verbose_name='Puesto')),
                ('linkedin_link', models.URLField(verbose_name='Link Linkedin')),
                ('linkedin_name', models.CharField(max_length=50, verbose_name='Nombre linkedin')),
                ('github_link', models.URLField(verbose_name='Link Github')),
                ('github_name', models.CharField(max_length=50, verbose_name='Nombre Github')),
                ('youtube_link', models.URLField(verbose_name='Link Youtube')),
                ('youtube_name', models.CharField(max_length=50, verbose_name='Nombre Youtube')),
                ('web_link', models.URLField(verbose_name='Link Sitio Web')),
                ('web_name', models.CharField(max_length=50, verbose_name='Nombre Sitio Web')),
                ('update', models.DateField(verbose_name='Actualizado')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Contacto')),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Informaciones',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='compañia')),
                ('job', models.CharField(max_length=150, verbose_name='Puesto')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('start_work', models.DateField(verbose_name='Desde')),
                ('end_work', models.DateField(null=True, verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Curso')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('start_course', models.DateField(verbose_name='Desde')),
                ('end_course', models.DateField(null=True, verbose_name='Hasta')),
                ('languages', models.ManyToManyField(blank=True, to='portafolio.language', verbose_name='Lenguajes')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
