# Generated by Django 4.1.5 on 2023-01-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='studying',
            field=models.BooleanField(null=True, verbose_name='Estudiando actualmente'),
        ),
        migrations.AddField(
            model_name='work',
            name='working',
            field=models.BooleanField(null=True, verbose_name='Trabajando actualmente'),
        ),
    ]
