# Generated by Django 4.1.5 on 2023-01-20 23:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_course_studying_work_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Descripción'),
        ),
    ]
